### ISSUE TITLE
"Choose language" missing for translation

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer-translations#3]
@species 

"Choose language" needs to be added to the menu translation items.

I just notice, as Lotta from Inkota reported that.

**Comment by species** [comment]
No, this will stay in English. Imagine you switched to a language you cannot even read (farsi?) and then want to go back ;-)

**Comment by josef-legacy-account** [comment]
@species 

> Imagine you switched to a language you cannot even read (farsi?) and then want to go back ;-)

That is a common problem, that people find. At the same time, people are quite irritated, if they find a non-native language string or button in their native language UI. 

Am I right in assuming, that by loading the site anew, it will be set either in the language of the browser, or in default english? So people would not get stuck.

---

**On one side** I would like to pledge for re-opening the issue and just adding the string to the translation system:
_As I am very sure, that we will get more requests, once all translations are done, and people wonder about this one_.
**On the other side** I am aware, that we got much more important issues to work on, so I will not insist and leave it with this post, even knowing, that it will produce more people wondering and emails flying around in the future.   ... does actually feel not so good.
