### ISSUE TITLE
languages missing in weblate translation

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer-translations#4]
@species please add the following languages:

Estonian
Finnish
French
Hungarian
Gaelic
Italian
Maltese
Slovakian
Slovenian
Spanish

**Comment by species** [comment]
Done.
btw, there were only 6 to add ([90a7a533c153a5704155bf902d44d85bbe1acf37](https://github.com/TransforMap/transformap-viewer-translations/commit/90a7a533c153a5704155bf902d44d85bbe1acf37?diff=unified])), the rest was here.

**Comment by josef-legacy-account** [comment]
Thx,

just noticed, that it seems confusing, that they are not displayed at the start screen, if not logged in. There are just some of them displayed there: https://weblate.transformap.co/
